title: mp19uy
description: My Personal Blog
author: Martin Pacheco	
logo: /static/img/avatar.png
github: https://github.com/mp19uy
about: Security Enthusiast

baseurl: ""
url: "http://mp19uy.github.io/"

disqus_shortname: mp19uy
google_analytics: UA-39025503-3

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
